### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Fjsksksk** [Clement-Szewczyk/La_Launay_Toons#1]
Ici nos questions pour chaque cours

**Comment by Fjsksksk** [comment]
1 | Pourquoi il nous arrive d'avoir une connaissance sur le bout de la langue sans réussir à la récupérer ?
	-> Car lors de l'encodage nous n'avons pas mis assez d'amorces pour récupérer l'information

2 | Quelle est la meilleure technique pour tester les connaissances acquises durant un cour ?
	-> Utilisé le rappel libre : écrire tout ce on se souvient sur une feuille

3 | Quelle méthode d'organisation des idées combine le textuel et le visuel ?
	-> La carte mentale

4 | Quel est l'élément le plus important dans le temps lors des révisions permettant un meilleur encodage et le développement des amorces ?
	-> La répétition

5 | Comment être sure que notre connaissance est dans la mémoire long-terme ?
	-> Grâce aux auto-tests

**Comment by totodicoco** [comment]
Quel sont les différences entre la mémoire a long terme et la mémoire de travail ?

Explique-moi le principe de répétition espacé par un schéma.

Pratiques-tu la technique de diversification dans ton travail ? Pourquoi ? 

Penses-tu que la carte mentale est une bonne technique d’apprentissage et de mémorisation ?

Explique-moi concrètement ce qu’est obsidian.

**Comment by Fjsksksk** [comment]
1 | Comment cloner un projet GitHub sur votre ordinateur ?
-> Utilisez la commande "git clone [URL du projet]" dans le terminal

2 | Comment synchronisez-vous vos commits locaux avec le dépôt distant sur GitHub ?
-> Utilisez la commande "git pull" dans le terminal

3 | Comment ajouté TOUTES vos modifications au commit ?
->  Utilisez la commande "git add . " dans le terminal

4 | Quelle commande vous permet de vérifier l'état des fichiers modifiés dans votre dépôt Git local ?
-> Utilisez la commande "git status " dans le terminal

5 | Qu'est-ce qu'une branche principale (main branch) dans un dépôt Git ?
-> La branche principale est souvent la branche par défaut d'un dépôt Git, elle représente la version stable du projet. Elle est importante car c'est à partir d'elle que sont créées et fusionnées d'autres branches

**Comment by totodicoco** [comment]
Qu'est-ce que Git ?
- Git est un outil de gestion de versions du code.

Quelle est la commande Git pour afficher l'état actuel du dépôt ?
- La commande Git pour afficher l'état actuel du dépôt est "git status".

Pourquoi est-il important de maîtriser Git dans le domaine de l'informatique ?
- Maîtriser Git est essentiel pour suivre l'historique du code, collaborer avec d'autres développeurs, et gérer efficacement les versions du code.

Comment peut-on créer un nouveau projet Git localement ?
- On peut créer un nouveau projet Git localement en utilisant la commande "git init" dans un nouveau répertoire.

Comment enregistrer localement un fichier git ?
- avec la commande git clone
